FROM node:22-alpine

WORKDIR /migrate

RUN corepack enable

COPY yarn.lock /tmp/yarn.lock

RUN export PRISMA_VERSION=$(grep -A 1 'prisma@' /tmp/yarn.lock | grep version | head -1 | awk -F\" '{print $2}')

RUN yarn add prisma@${PRISMA_VERSION}

COPY ./prisma ./prisma

CMD ["yarn","prisma", "migrate", "deploy"]